[application]
name = "page"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "page"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
